FROM docker.io/php:8.3-apache

WORKDIR /var/www/html

# PHP
RUN apt-get update && apt-get upgrade
RUN apt-get install -y zlib1g-dev libwebp-dev libpng-dev && docker-php-ext-install gd
RUN apt-get install libzip-dev -y && docker-php-ext-install zip
RUN docker-php-ext-configure pdo_mysql
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-enable pdo_mysql

# Apache
RUN a2enmod rewrite
RUN service apache2 restart

# Composer
##RUN apk update && apk add curl && \
##  curl -sS https://getcomposer.org/installer | php \
##  && chmod +x composer.phar && mv composer.phar /usr/local/bin/composer

EXPOSE 80