services:
   monapache:
      ports:
      - "8888:80"
      networks:
      - netapp
      build: .
      volumes:
      - ./:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
   bdd:
      container_name: 'bdd'
      image: mysql:8.1.0
      ports:
         - 3303:3306
      environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: _wshop_test
         MYSQL_USER: root
         MYSQL_PASSWORD: root
      volumes:
         - ./mysql_data:/var/lib/mysql 
      networks:
         - netbdd
   adminer:
      image: adminer
      restart: always
      ports:
      - 8080:8080
      environment:
         ADMINER_DEFAULT_SERVER: mysql_server
      networks:
         - netbdd
volumes:
   mysql_data:

networks:
   netapp: {}
   netbdd: {}