services:
   monapacheapi:
      ports:
      - "8000:80"
      build: .
      volumes:
      - .:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
   bddapi:
      container_name: bddapi
      image: mysql:8.1.0
      ports:
         - 3309:3306
      environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: api_magasin
      volumes:
         - ./mysql_data:/var/lib/mysql
   adminerapi:
      image: adminer
      restart: always
      ports:
      - 8082:8080
      environment:
         ADMINER_DEFAULT_SERVER: mysql_server

volumes:
   mysql_data: