version: "3.9"
services:
   php-apache:
      ports:
      - "8080:80"
      build: './build/php'
      volumes:
      - ./:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
   mysql:

      container_name: 'mysql'
      image: mysql:8.1.0
      ports:
         - 3307:3306
      environment:
         MYSQL_ROOT_PASSWORD: 'password'
         MYSQL_DATABASE: 'db'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: 'password'
      volumes:
         - ./mysql_data:/var/lib/mysql 
      networks:
         - netbdd
volumes:
   app:
   netbdd: